#!/bin/sh

set -e

# "noauto" is what live-build checks for: it tells lb config this call is the
# real config generation, not another redirect into auto/config (which would
# recurse forever). Any other first argument re-runs this script in place.
lb config noauto "${@}" \
    --mode debian \
    --architectures amd64 \
    --linux-flavours amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --parent-mirror-chroot "http://deb.debian.org/debian/" \
    --parent-mirror-binary "http://deb.debian.org/debian/" \
    --security true \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    --parent-mirror-chroot-security "http://security.debian.org/debian-security" \
    --parent-mirror-binary-security "http://security.debian.org/debian-security" \
    --keyring-packages debian-archive-keyring \
    --system live \
    --initsystem systemd \
    --binary-images iso-hybrid \
    --iso-application "Raptor OS Security" \
    --iso-volume "RAPTOR-SECURITY" \
    --apt-indices false \
    --apt-recommends true \
    --cache-stages "" \
    --bootappend-live "boot=live config components username=user autologin ignore_uuid live-media-timeout=30"
