#!/bin/sh

set -e

lb config nooption "${@}" \
    --mode debian \
    --architectures amd64 \
    --linux-flavours amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --parent-mirror-chroot "http://deb.debian.org/debian/" \
    --parent-mirror-binary "http://deb.debian.org/debian/" \
    --security true \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    --parent-mirror-chroot-security "http://security.debian.org/debian-security" \
    --parent-mirror-binary-security "http://security.debian.org/debian-security" \
    --keyring-packages debian-archive-keyring \
    --system live \
    --binary-images iso-hybrid \
    --apt-indices false \
    --apt-recommends true
